#!/bin/bash
# VPS Installer
# Script by Juan
# 
# Illegal selling and redistribution of this script is strictly prohibited
# Please respect author's Property
# Binigay sainyo ng libre, ipamahagi nyo rin ng libre.
#
#

 # Now check if our machine is in root user, if not, this script exits
 # If you're on sudo user, run `sudo su -` first before running this script
if [[ $EUID -ne 0 ]];then
 ScriptMessage
 echo -e "[\e[1;31mError\e[0m] This script must be run as root, exiting..."
 exit 1
fi
MyScriptName='FreenetCafe'
SSH_Port1='22'
SSH_Port2='225'
SSH_Banner='https://github.com/yakult13/parte/raw/main/cafe'
Dropbear_Port1='550'
Dropbear_Port2='555'
Stunnel_Port1='443'
Stunnel_Port2='444'
Proxy_Port1='8080'
Proxy_Port2='8000'
OpenVPN_Port1='110'
OpenVPN_Port2='112'
OpenVPN_Port3='1194'
OpenVPN_Port4='25888'
Privoxy_Port1='8686'
Privoxy_Port2='8787'
OvpnDownload_Port='1998'
MyVPS_Time='Asia/Manila'

IPADDR="$(curl -4skL http://ipinfo.io/ip)"

function  Instupdate() {
export DEBIAN_FRONTEND=noninteractive
 apt-get update
 apt-get upgrade -y
 apt install fail2ban -y
 apt-get remove --purge ufw firewalld -y
 apt-get install nano wget curl zip unzip tar gzip p7zip-full bc rc openssl cron net-tools dnsutils dos2unix screen bzip2 ccrypt -y
 apt-get install dropbear stunnel4 privoxy ca-certificates nginx ruby apt-transport-https lsb-release squid screenfetch -y
 apt-get install perl libnet-ssleay-perl openssl libauthen-pam-perl libpam-runtime libio-pty-perl apt-show-versions python dbus libxml-parser-perl -y
 apt-get install shared-mime-info jq -y
 gem install lolcat
 apt-get autoremove -y
 echo "deb http://build.openvpn.net/debian/openvpn/stable $(lsb_release -sc) main" >/etc/apt/sources.list.d/openvpn.list && apt-key del E158C569 && wget -O - https://swupdate.openvpn.net/repos/repo-public.gpg | apt-key add -
 wget -qO security-openvpn-net.asc "https://keys.openpgp.org/vks/v1/by-fingerprint/F554A3687412CFFEBDEFE0A312F5F7B42F2B01E7" && gpg --import security-openvpn-net.asc
 apt-get update -y
 apt-get install openvpn -y
}

function InstWebmin(){
 WebminFile='http://prdownloads.sourceforge.net/webadmin/webmin_1.910_all.deb'
 wget -qO webmin.deb "$WebminFile"
 dpkg --install webmin.deb
 rm -rf webmin.deb
 sed -i 's|ssl=1|ssl=0|g' /etc/webmin/miniserv.conf
 systemctl restart webmin
}

function InstSSH(){
 rm -f /etc/ssh/sshd_config*
 cat <<'MySSHConfig' > /etc/ssh/sshd_config
# My OpenSSH Server config
Port myPORT1
Port myPORT2
AddressFamily inet
ListenAddress 0.0.0.0
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
PermitRootLogin yes
MaxSessions 1024
PubkeyAuthentication yes
PasswordAuthentication yes
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes
X11Forwarding yes
PrintMotd no
ClientAliveInterval 240
ClientAliveCountMax 2
UseDNS no
Banner /etc/banner
AcceptEnv LANG LC_*
Subsystem   sftp  /usr/lib/openssh/sftp-server
MySSHConfig

 sed -i "s|myPORT1|$SSH_Port1|g" /etc/ssh/sshd_config
 sed -i "s|myPORT2|$SSH_Port2|g" /etc/ssh/sshd_config

 rm -f /etc/banner
 wget -qO /etc/banner "$SSH_Banner"
 dos2unix -q /etc/banner

 sed -i '/password\s*requisite\s*pam_cracklib.s.*/d' /etc/pam.d/common-password
 sed -i 's/use_authtok //g' /etc/pam.d/common-password
 sed -i '/\/bin\/false/d' /etc/shells
 sed -i '/\/usr\/sbin\/nologin/d' /etc/shells
 echo '/bin/false' >> /etc/shells
 echo '/usr/sbin/nologin' >> /etc/shells
 
 systemctl restart ssh

 rm -rf /etc/default/dropbear*
 
 # creating dropbear config using cat eof tricks
 cat <<'MyDropbear' > /etc/default/dropbear
# My Dropbear Config
NO_START=0
DROPBEAR_PORT=PORT01
DROPBEAR_EXTRA_ARGS="-p PORT02"
DROPBEAR_BANNER="/etc/banner"
DROPBEAR_RSAKEY="/etc/dropbear/dropbear_rsa_host_key"
DROPBEAR_DSSKEY="/etc/dropbear/dropbear_dss_host_key"
DROPBEAR_ECDSAKEY="/etc/dropbear/dropbear_ecdsa_host_key"
DROPBEAR_RECEIVE_WINDOW=65536
MyDropbear

 # Now changing our desired dropbear ports
 sed -i "s|PORT01|$Dropbear_Port1|g" /etc/default/dropbear
 sed -i "s|PORT02|$Dropbear_Port2|g" /etc/default/dropbear
 
 # Restarting dropbear service
 systemctl restart dropbear
}

function InsStunnel(){
 StunnelDir=$(ls /etc/default | grep stunnel | head -n1)

 # Creating stunnel startup config using cat eof tricks
cat <<'MyStunnelD' > /etc/default/$StunnelDir
# My Stunnel Config
ENABLED=1
FILES="/etc/stunnel/*.conf"
OPTIONS="/etc/banner"
BANNER="/etc/banner"
PPP_RESTART=0
# RLIMITS="-n 4096 -d unlimited"
RLIMITS=""
MyStunnelD

 # Removing all stunnel folder contents
 rm -rf /etc/stunnel/*
 
 # Creating stunnel certifcate using openssl
 openssl req -new -x509 -days 9999 -nodes -subj "/C=PH/ST=NCR/L=Manila/O=$MyScriptName/OU=$MyScriptName/CN=$MyScriptName" -out /etc/stunnel/stunnel.pem -keyout /etc/stunnel/stunnel.pem &> /dev/null
##  > /dev/null 2>&1

 # Creating stunnel server config
 cat <<'MyStunnelC' > /etc/stunnel/stunnel.conf
# My Stunnel Config
pid = /var/run/stunnel.pid
cert = /etc/stunnel/stunnel.pem
client = no
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
TIMEOUTclose = 0

[dropbear]
accept = Stunnel_Port1
connect = 127.0.0.1:dropbear_port_c

[openssh]
accept = Stunnel_Port2
connect = 127.0.0.1:openssh_port_c
MyStunnelC

 # setting stunnel ports
 sed -i "s|Stunnel_Port1|$Stunnel_Port1|g" /etc/stunnel/stunnel.conf
 sed -i "s|dropbear_port_c|$(netstat -tlnp | grep -i dropbear | awk '{print $4}' | cut -d: -f2 | xargs | awk '{print $2}' | head -n1)|g" /etc/stunnel/stunnel.conf
 sed -i "s|Stunnel_Port2|$Stunnel_Port2|g" /etc/stunnel/stunnel.conf
 sed -i "s|openssh_port_c|$(netstat -tlnp | grep -i ssh | awk '{print $4}' | cut -d: -f2 | xargs | awk '{print $2}' | head -n1)|g" /etc/stunnel/stunnel.conf

 # Restarting stunnel service
 systemctl restart $StunnelDir

}

function InsOpenVPN(){
 # Checking if openvpn folder is accidentally deleted or purged
 if [[ ! -e /etc/openvpn ]]; then
  mkdir -p /etc/openvpn
 fi

 # Removing all existing openvpn server files
 rm -rf /etc/openvpn/*

 # Creating server.conf, ca.crt, server.crt and server.key
 cat <<'VPN1' > /etc/openvpn/server_tcp.conf
port MyOvpnPort1
proto tcp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh.pem
server 172.18.0.0 255.255.0.0
ifconfig-pool-persist /etc/openvpn/ipp.txt
duplicate-cn
keepalive 10 120
tls-crypt ta.key
compress lz4-v2
max-clients 4000
user nobody
group nogroup
persist-key
persist-tun
status /etc/openvpn/openvpn-status.log
log /etc/openvpn/openvpn.log
verb 3
mute 20
topology subnet
ecdh-curve secp521r1
explicit-exit-notify 0
cipher AES-128-CBC
ncp-ciphers AES-128-CBC
auth SHA512
push "redirect-gateway def1 bypass-dhcp"
socket-flags TCP_NODELAY
push "socket-flags TCP_NODELAY"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
tls-server
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
VPN1

cat <<'VPN2' > /etc/openvpn/server_tcp1.conf
port MyOvpnPort2
proto tcp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh.pem
server 172.19.0.0 255.255.0.0
ifconfig-pool-persist /etc/openvpn/ipp.txt
duplicate-cn
keepalive 10 120
tls-crypt ta.key
compress lz4-v2
max-clients 4000
user nobody
group nogroup
persist-key
persist-tun
status /etc/openvpn/openvpn-status.log
log /etc/openvpn/openvpn.log
verb 3
mute 20
topology subnet
ecdh-curve secp521r1
explicit-exit-notify 0
cipher AES-128-CBC
ncp-ciphers AES-128-CBC
auth SHA512
push "redirect-gateway def1 bypass-dhcp"
socket-flags TCP_NODELAY
push "socket-flags TCP_NODELAY"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
tls-server
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
VPN2

 cat <<'VPN3' > /etc/openvpn/server_udp.conf
port MyOvpnPort3
proto udp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh.pem
server 172.20.0.0 255.255.0.0
ifconfig-pool-persist /etc/openvpn/ipp.txt
duplicate-cn
keepalive 10 120
tls-crypt ta.key
compress lz4-v2
max-clients 4000
user nobody
group nogroup
persist-key
persist-tun
status /etc/openvpn/openvpn-status.log
log /etc/openvpn/openvpn.log
verb 3
mute 20
topology subnet
ecdh-curve secp521r1
explicit-exit-notify 0
cipher AES-128-CBC
ncp-ciphers AES-128-CBC
auth SHA512
push "redirect-gateway def1 bypass-dhcp"
socket-flags TCP_NODELAY
push "socket-flags TCP_NODELAY"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
tls-server
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
VPN3

 cat <<'VPN4' > /etc/openvpn/server_udp1.conf
port MyOvpnPort4
proto udp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh.pem
server 172.21.0.0 255.255.0.0
ifconfig-pool-persist /etc/openvpn/ipp.txt
duplicate-cn
keepalive 10 120
tls-crypt ta.key
compress lz4-v2
max-clients 4000
user nobody
group nogroup
persist-key
persist-tun
status /etc/openvpn/openvpn-status.log
log /etc/openvpn/openvpn.log
verb 3
mute 20
topology subnet
ecdh-curve secp521r1
explicit-exit-notify 0
cipher AES-128-CBC
ncp-ciphers AES-128-CBC
auth SHA512
push "redirect-gateway def1 bypass-dhcp"
socket-flags TCP_NODELAY
push "socket-flags TCP_NODELAY"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
tls-server
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
VPN4

 cat <<'CERT'> /etc/openvpn/ca.crt
-----BEGIN CERTIFICATE-----
MIICSjCCAaugAwIBAgIUFEtB8rfQzITHeQLZF6fUnYsv5wgwCgYIKoZIzj0EAwQw
FzEVMBMGA1UEAwwMRlJFRU5FVF9DQUZFMB4XDTIyMDQwNzA5MDUyOFoXDTMyMDQw
NDA5MDUyOFowFzEVMBMGA1UEAwwMRlJFRU5FVF9DQUZFMIGbMBAGByqGSM49AgEG
BSuBBAAjA4GGAAQBy/n6u92Pi3XZSc8R6ZEZn3jib1IQG6f3bAgGjAqayRnDVo6M
JK0kf02wi/b7+XPdY21nnL3dVKFDjZBPJU+FcBMA/M2YRWciiDxnFURybvXQudW9
MqtW4X1Sr1+IP1JNPwBlv/NdPuhZzmyZg7L3st0n48OauuxEpiKFK+yMulVCLuCj
gZEwgY4wHQYDVR0OBBYEFPUKRLqRwqUxMPpIdrBgWsxplqocMFIGA1UdIwRLMEmA
FPUKRLqRwqUxMPpIdrBgWsxplqocoRukGTAXMRUwEwYDVQQDDAxGUkVFTkVUX0NB
RkWCFBRLQfK30MyEx3kC2Ren1J2LL+cIMAwGA1UdEwQFMAMBAf8wCwYDVR0PBAQD
AgEGMAoGCCqGSM49BAMEA4GMADCBiAJCAWO0F7uls5t4HvfvKKCjiL2HS5+XEHCb
zjUbc68TF4Vn4meofXWJGiIiQn9EzkU4kP83eZV5tYoqvCEn7YNF6p+sAkIBA42K
bIT+XWBWJH59ynzUmsnmLHM0PGDvnHRmrP6btOzppt0k42dm+2kXPS5dVIF2Z+9C
vxn9Q7gBrdo3sE+VwXE=
-----END CERTIFICATE-----
CERT

 cat <<'SCERT'> /etc/openvpn/server.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            b6:ea:75:2f:24:22:f4:2c:90:ab:05:f8:2b:e0:6e:e0
        Signature Algorithm: ecdsa-with-SHA512
        Issuer: CN=FREENET_CAFE
        Validity
            Not Before: Apr  7 09:07:34 2022 GMT
            Not After : Apr  4 09:07:34 2032 GMT
        Subject: CN=FREENET_CAFE
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (521 bit)
                pub:
                    04:00:94:7b:84:fe:8a:72:f8:92:f7:0d:25:4b:f0:
                    c1:ec:6f:98:d7:21:02:d8:44:43:a3:bc:a7:de:7b:
                    dc:ab:76:1a:98:98:2d:d3:6d:41:a1:3d:4f:72:86:
                    cb:b4:1e:f6:fd:71:cd:ea:5c:8e:a7:17:eb:1e:46:
                    4a:94:c6:cf:20:65:22:01:b8:15:c8:59:45:04:7c:
                    4e:9e:72:eb:7e:29:eb:49:a8:3f:d8:5b:64:4f:1f:
                    3f:da:ca:e0:6e:dc:d2:00:48:6d:b5:12:a3:c5:57:
                    a6:48:61:5a:be:6b:96:13:3c:2e:09:e7:bf:e9:a3:
                    b6:ee:a0:61:22:61:76:0c:5f:f7:e6:86:24
                ASN1 OID: secp521r1
                NIST CURVE: P-521
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Subject Key Identifier: 
                2B:39:F8:2F:D7:36:D4:E5:B8:7C:8E:00:65:A1:BA:C1:86:86:94:F4
            X509v3 Authority Key Identifier: 
                keyid:F5:0A:44:BA:91:C2:A5:31:30:FA:48:76:B0:60:5A:CC:69:96:AA:1C
                DirName:/CN=FREENET_CAFE
                serial:14:4B:41:F2:B7:D0:CC:84:C7:79:02:D9:17:A7:D4:9D:8B:2F:E7:08

            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Key Usage: 
                Digital Signature, Key Encipherment
            X509v3 Subject Alternative Name: 
                DNS:FREENET_CAFE
    Signature Algorithm: ecdsa-with-SHA512
         30:81:88:02:42:01:4e:16:69:18:49:2e:d6:d6:29:ab:42:b3:
         72:04:98:6a:1c:8a:44:e3:b5:e1:e9:b0:8b:5a:47:a1:5f:80:
         35:02:8e:07:28:0d:d4:b9:e4:3f:f9:dd:61:88:bf:7d:79:e2:
         5d:f7:db:a5:8c:e7:75:39:51:e1:5c:f8:db:d6:4d:aa:98:02:
         42:00:d8:80:03:26:70:b4:ce:3a:12:c2:fe:a3:2c:50:85:8f:
         7d:13:63:81:64:a1:57:f0:10:a3:1d:8b:0a:4e:5e:96:14:73:
         52:b6:8e:ca:77:e8:5a:80:3c:34:32:56:b0:e6:c8:7c:d2:3f:
         9c:0b:76:8c:1b:f1:39:57:a0:cc:c0:b9:af
-----BEGIN CERTIFICATE-----
MIICcjCCAdOgAwIBAgIRALbqdS8kIvQskKsF+CvgbuAwCgYIKoZIzj0EAwQwFzEV
MBMGA1UEAwwMRlJFRU5FVF9DQUZFMB4XDTIyMDQwNzA5MDczNFoXDTMyMDQwNDA5
MDczNFowFzEVMBMGA1UEAwwMRlJFRU5FVF9DQUZFMIGbMBAGByqGSM49AgEGBSuB
BAAjA4GGAAQAlHuE/opy+JL3DSVL8MHsb5jXIQLYREOjvKfee9yrdhqYmC3TbUGh
PU9yhsu0Hvb9cc3qXI6nF+seRkqUxs8gZSIBuBXIWUUEfE6ecut+KetJqD/YW2RP
Hz/ayuBu3NIASG21EqPFV6ZIYVq+a5YTPC4J57/po7buoGEiYXYMX/fmhiSjgbww
gbkwCQYDVR0TBAIwADAdBgNVHQ4EFgQUKzn4L9c21OW4fI4AZaG6wYaGlPQwUgYD
VR0jBEswSYAU9QpEupHCpTEw+kh2sGBazGmWqhyhG6QZMBcxFTATBgNVBAMMDEZS
RUVORVRfQ0FGRYIUFEtB8rfQzITHeQLZF6fUnYsv5wgwEwYDVR0lBAwwCgYIKwYB
BQUHAwEwCwYDVR0PBAQDAgWgMBcGA1UdEQQQMA6CDEZSRUVORVRfQ0FGRTAKBggq
hkjOPQQDBAOBjAAwgYgCQgFOFmkYSS7W1imrQrNyBJhqHIpE47Xh6bCLWkehX4A1
Ao4HKA3UueQ/+d1hiL99eeJd99uljOd1OVHhXPjb1k2qmAJCANiAAyZwtM46EsL+
oyxQhY99E2OBZKFX8BCjHYsKTl6WFHNSto7Kd+hagDw0Mlaw5sh80j+cC3aMG/E5
V6DMwLmv
-----END CERTIFICATE-----
SCERT

 cat <<'SKEY' > /etc/openvpn/server.key
-----BEGIN PRIVATE KEY-----
MIHuAgEAMBAGByqGSM49AgEGBSuBBAAjBIHWMIHTAgEBBEIBD6K9tfZQ57C1O/kg
L/jgPTWjoJX+75+gIS7SLq//sfEPkeU5d7tHBMOiHOjte0VeCeWP25WH6nBZqc3o
11kfReehgYkDgYYABACUe4T+inL4kvcNJUvwwexvmNchAthEQ6O8p9573Kt2GpiY
LdNtQaE9T3KGy7Qe9v1xzepcjqcX6x5GSpTGzyBlIgG4FchZRQR8Tp5y634p60mo
P9hbZE8fP9rK4G7c0gBIbbUSo8VXpkhhWr5rlhM8Lgnnv+mjtu6gYSJhdgxf9+aG
JA==
-----END PRIVATE KEY-----
SKEY

cat <<'TAK' > /etc/openvpn/ta.key
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
571a0867b2e8f0e5a1c316522b260d59
a9fc7348d0cee6c8df6dd8bdb93020f1
87cf5807c2546dec108e6a1b826dcbcd
e79ac36aecf1cde9c448938862dde674
566668a8c4e9ff8ea9dbe712adcf0a81
a3fc8e56ed8cd9d9b3ae7acdb076f49d
b31834cc27d29620e850900bca423f0f
58475567f7ae224a81872483ab916703
5a9e2ffe7648e98f9abcbabfd8e1815f
33b7ecbc5e9e4a5211e773d16f78fee4
4c75adf6c7f87b113e8b9ddfcc7d93e8
a6e16490d09e230cece1d5b9912c8378
ab88e1b04476eee3d6a429f1ae745407
9715211110512f40553105e064697388
78f2610f6db2f88e7f0d007e28e931bf
d1b11e8d6f6ef7b6a52c2c838acee6ab
-----END OpenVPN Static key V1-----
TAK

cat <<'clientkey' > /etc/openvpn/ckey.key
-----BEGIN PRIVATE KEY-----
MIHuAgEAMBAGByqGSM49AgEGBSuBBAAjBIHWMIHTAgEBBEIBY+w1a0q6Q0qKRvDi
DPVr2b4T2xIq0EqdDpSwd5OzVi/mDGvRAWNJj8TP7ZCz8ZdD79oe/OYnw6omRTFs
HxpbIcyhgYkDgYYABADPwUGuprxBoG2wIB2RLYRwCQhMKV/kL/Gk6wVG02txkWzz
JUzVTkhQAGwxZKmDJDhRBB0MkzvPs3RA3iyUUnJgKQBWM8ih2ka4dTn9/Vb2tf/j
+ptdsEPq2qk2VqwX44438VyByqR5Ge5QVLtlQC65oIgZJUGI/IbC7ZM3GEGg/EbE
2g==
-----END PRIVATE KEY-----
clientkey

cat <<'dh' > /etc/openvpn/dh.pem
-----BEGIN DH PARAMETERS-----
MIIBCAKCAQEA8Om2VDkLqOBSh6AF638LqhK7z+REPt9KuJzgC4PX75frM24LvKXG
w5RarYdHbTTcpuvREYiGpwRszjqRzx1BlrDnKoWkTFTLxpGXKJW5I1Rammt1AqSs
7ILWgDmx5eBpTNOondsNdO+cT11mkVyohLbO11sJXfv7F34PXDxx8LHe7Nf13jFr
K1kEUW0MoPa5aARxdgQiVXzo4VlgxfX1Z3q0s2PtmiGB0LtYYMQYGYwR6qGK/M4g
VO1xDGURbRSmOniN18g7+45xq+voRtXHgedLB6Vdv4UYRQdldhBgEvKHm5SR45kn
HOlq8FVOtFl/z7qiiZqMS5JB2awWAJ8bWwIBAg==
-----END DH PARAMETERS-----
dh

cat <<'clientcert' > /etc/openvpn/ccert.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            d2:6c:e9:7a:db:dd:46:ed:27:60:e7:2d:23:e3:af:6c
        Signature Algorithm: ecdsa-with-SHA512
        Issuer: CN=FREENET_CAFE
        Validity
            Not Before: Apr  7 09:13:41 2022 GMT
            Not After : Apr  4 09:13:41 2032 GMT
        Subject: CN=FREENET_USER
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (521 bit)
                pub:
                    04:00:cf:c1:41:ae:a6:bc:41:a0:6d:b0:20:1d:91:
                    2d:84:70:09:08:4c:29:5f:e4:2f:f1:a4:eb:05:46:
                    d3:6b:71:91:6c:f3:25:4c:d5:4e:48:50:00:6c:31:
                    64:a9:83:24:38:51:04:1d:0c:93:3b:cf:b3:74:40:
                    de:2c:94:52:72:60:29:00:56:33:c8:a1:da:46:b8:
                    75:39:fd:fd:56:f6:b5:ff:e3:fa:9b:5d:b0:43:ea:
                    da:a9:36:56:ac:17:e3:8e:37:f1:5c:81:ca:a4:79:
                    19:ee:50:54:bb:65:40:2e:b9:a0:88:19:25:41:88:
                    fc:86:c2:ed:93:37:18:41:a0:fc:46:c4:da
                ASN1 OID: secp521r1
                NIST CURVE: P-521
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Subject Key Identifier: 
                14:46:75:93:2C:62:37:2B:40:06:66:F4:12:4F:39:F0:E3:BB:C6:1D
            X509v3 Authority Key Identifier: 
                keyid:F5:0A:44:BA:91:C2:A5:31:30:FA:48:76:B0:60:5A:CC:69:96:AA:1C
                DirName:/CN=FREENET_CAFE
                serial:14:4B:41:F2:B7:D0:CC:84:C7:79:02:D9:17:A7:D4:9D:8B:2F:E7:08

            X509v3 Extended Key Usage: 
                TLS Web Client Authentication
            X509v3 Key Usage: 
                Digital Signature
    Signature Algorithm: ecdsa-with-SHA512
         30:81:87:02:41:1e:a0:76:b4:5c:b2:15:f1:84:38:c3:5f:2f:
         4f:16:f4:3d:e0:5a:e9:12:a6:6c:70:59:57:00:ec:e5:21:d1:
         3d:13:6c:db:1e:11:57:75:9e:81:07:4d:5b:fb:cd:e4:0e:85:
         9d:da:ef:c5:31:c5:97:25:41:e5:d5:5e:8e:2b:d2:89:02:42:
         01:c0:54:5c:ba:67:1e:89:66:66:0f:1c:99:c8:9c:ac:5b:a0:
         2c:3a:d2:b3:95:53:d3:b0:db:20:b9:c3:0e:22:6e:11:ce:a3:
         82:ea:47:7e:49:65:e9:dd:4b:72:de:fd:32:d2:ca:91:49:1a:
         c3:06:a7:e8:c4:2b:f0:b9:f3:96:ca:4e
-----BEGIN CERTIFICATE-----
MIICWDCCAbqgAwIBAgIRANJs6Xrb3UbtJ2DnLSPjr2wwCgYIKoZIzj0EAwQwFzEV
MBMGA1UEAwwMRlJFRU5FVF9DQUZFMB4XDTIyMDQwNzA5MTM0MVoXDTMyMDQwNDA5
MTM0MVowFzEVMBMGA1UEAwwMRlJFRU5FVF9VU0VSMIGbMBAGByqGSM49AgEGBSuB
BAAjA4GGAAQAz8FBrqa8QaBtsCAdkS2EcAkITClf5C/xpOsFRtNrcZFs8yVM1U5I
UABsMWSpgyQ4UQQdDJM7z7N0QN4slFJyYCkAVjPIodpGuHU5/f1W9rX/4/qbXbBD
6tqpNlasF+OON/FcgcqkeRnuUFS7ZUAuuaCIGSVBiPyGwu2TNxhBoPxGxNqjgaMw
gaAwCQYDVR0TBAIwADAdBgNVHQ4EFgQUFEZ1kyxiNytABmb0Ek858OO7xh0wUgYD
VR0jBEswSYAU9QpEupHCpTEw+kh2sGBazGmWqhyhG6QZMBcxFTATBgNVBAMMDEZS
RUVORVRfQ0FGRYIUFEtB8rfQzITHeQLZF6fUnYsv5wgwEwYDVR0lBAwwCgYIKwYB
BQUHAwIwCwYDVR0PBAQDAgeAMAoGCCqGSM49BAMEA4GLADCBhwJBHqB2tFyyFfGE
OMNfL08W9D3gWukSpmxwWVcA7OUh0T0TbNseEVd1noEHTVv7zeQOhZ3a78UxxZcl
QeXVXo4r0okCQgHAVFy6Zx6JZmYPHJnInKxboCw60rOVU9Ow2yC5ww4ibhHOo4Lq
R35JZendS3Le/TLSypFJGsMGp+jEK/C585bKTg==
-----END CERTIFICATE-----
clientcert

 # setting openvpn server port
 sed -i "s|MyOvpnPort1|$OpenVPN_Port1|g" /etc/openvpn/server_tcp.conf
 sed -i "s|MyOvpnPort2|$OpenVPN_Port2|g" /etc/openvpn/server_tcp1.conf
 sed -i "s|MyOvpnPort3|$OpenVPN_Port3|g" /etc/openvpn/server_udp.conf
 sed -i "s|MyOvpnPort4|$OpenVPN_Port4|g" /etc/openvpn/server_udp1.conf
 
 # Getting some OpenVPN plugins for unix authentication
 #wget -qO /etc/openvpn/b.zip 'https://github.com/imaPSYCHO/Parts/raw/main/openvpn_plugin64'
 #unzip -qq /etc/openvpn/b.zip -d /etc/openvpn
 #rm -f /etc/openvpn/b.zip
 
 # Some workaround for OpenVZ machines for "Startup error" openvpn service
 if [[ "$(hostnamectl | grep -i Virtualization | awk '{print $2}' | head -n1)" == 'openvz' ]]; then
 sed -i 's|LimitNPROC|#LimitNPROC|g' /lib/systemd/system/openvpn*
 systemctl daemon-reload
fi

 # Allow IPv4 Forwarding
 echo 'net.ipv4.ip_forward=1' > /etc/sysctl.d/20-openvpn.conf && sysctl --system &> /dev/null && echo 1 > /proc/sys/net/ipv4/ip_forward

 # Installing Firewalld
 apt install firewalld -y
 systemctl start firewalld
 systemctl enable firewalld
 firewall-cmd --quiet --set-default-zone=public
 firewall-cmd --quiet --zone=public --permanent --add-port=1-65534/tcp
 firewall-cmd --quiet --zone=public --permanent --add-port=1-65534/udp
 firewall-cmd --quiet --reload
 firewall-cmd --quiet --add-masquerade
 firewall-cmd --quiet --permanent --add-masquerade
 firewall-cmd --quiet --permanent --add-service=ssh
 firewall-cmd --quiet --permanent --add-service=openvpn
 firewall-cmd --quiet --permanent --add-service=http
 firewall-cmd --quiet --permanent --add-service=https
 firewall-cmd --quiet --permanent --add-service=privoxy
 firewall-cmd --quiet --permanent --add-service=squid
 firewall-cmd --quiet --reload
 
 # Enabling IPv4 Forwarding
 echo 1 > /proc/sys/net/ipv4/ip_forward

 
 # Starting OpenVPN server
 systemctl start openvpn@server_tcp
 systemctl start openvpn@server_tcp1
 systemctl start openvpn@server_udp
 systemctl start openvpn@server_udp1
 systemctl enable openvpn@server_tcp
 systemctl enable openvpn@server_tcp1
 systemctl enable openvpn@server_udp
 systemctl enable openvpn@server_udp1
 systemctl restart openvpn@server_tcp
 systemctl restart openvpn@server_tcp1
 systemctl restart openvpn@server_udp
 systemctl restart openvpn@server_udp1
}

function InsProxy(){
 # Removing Duplicate privoxy config
 rm -rf /etc/privoxy/config*
 
 # Creating Privoxy server config using cat eof tricks
 cat <<'myPrivoxy' > /etc/privoxy/config
# My Privoxy Server Config
user-manual /usr/share/doc/privoxy/user-manual
confdir /etc/privoxy
logdir /var/log/privoxy
filterfile default.filter
logfile logfile
listen-address 0.0.0.0:Privoxy_Port1
listen-address 0.0.0.0:Privoxy_Port2
toggle 1
enable-remote-toggle 0
enable-remote-http-toggle 0
enable-edit-actions 0
enforce-blocks 0
buffer-limit 4096
enable-proxy-authentication-forwarding 1
forwarded-connect-retries 1
accept-intercepted-requests 1
allow-cgi-request-crunching 1
split-large-forms 0
keep-alive-timeout 5
tolerate-pipelining 1
socket-timeout 300
permit-access 0.0.0.0/0 IP-ADDRESS
myPrivoxy

 # Setting machine's IP Address inside of our privoxy config(security that only allows this machine to use this proxy server)
 sed -i "s|IP-ADDRESS|$IPADDR|g" /etc/privoxy/config
 
 # Setting privoxy ports
 sed -i "s|Privoxy_Port1|$Privoxy_Port1|g" /etc/privoxy/config
 sed -i "s|Privoxy_Port2|$Privoxy_Port2|g" /etc/privoxy/config

 # I'm setting Some Squid workarounds to prevent Privoxy's overflowing file descriptors that causing 50X error when clients trying to connect to your proxy server(thanks for this trick @homer_simpsons)
 apt remove --purge squid -y
 rm -rf /etc/squid/sq*
 apt install squid -y
 
# Squid Ports (must be 1024 or higher)

 cat <<mySquid > /etc/squid/squid.conf
acl VPN dst $(wget -4qO- http://ipinfo.io/ip)/32
http_access allow VPN
http_access deny all 
http_port 0.0.0.0:$Proxy_Port1
http_port 0.0.0.0:$Proxy_Port2
coredump_dir /var/spool/squid
dns_nameservers 1.1.1.1 1.0.0.1
refresh_pattern ^ftp: 1440 20% 10080
refresh_pattern ^gopher: 1440 0% 1440
refresh_pattern -i (/cgi-bin/|\?) 0 0% 0
refresh_pattern . 0 20% 4320
visible_hostname localhost
mySquid

 sed -i "s|SquidCacheHelper|$Proxy_Port1|g" /etc/squid/squid.conf
 sed -i "s|SquidCacheHelper|$Proxy_Port2|g" /etc/squid/squid.conf

sudo apt install ziproxy
 cat <<myziproxy > /etc/ziproxy/ziproxy.conf
 Port = 2898
 UseContentLength = false
 ImageQuality = {30,25,25,20}
myziproxy

 # Starting Proxy server
 echo -e "Restarting proxy server.."
 systemctl restart privoxy
 systemctl restart squid
 systemctl restart ziproxy
}

function OvpnConfigs(){
 # Creating nginx config for our ovpn config downloads webserver
 cat <<'myNginxC' > /etc/nginx/conf.d/bonveio-ovpn-config.conf
# My OpenVPN Config Download Directory
server {
 listen 0.0.0.0:myNginx;
 server_name localhost;
 root /var/www/openvpn;
 index index.html;
}
myNginxC

 # Setting our nginx config port for .ovpn download site
 sed -i "s|myNginx|$OvpnDownload_Port|g" /etc/nginx/conf.d/bonveio-ovpn-config.conf

 # Removing Default nginx page(port 80)
 rm -rf /etc/nginx/sites-*

 # Creating our root directory for all of our .ovpn configs
 rm -rf /var/www/openvpn
 mkdir -p /var/www/openvpn

 # Now creating all of our OpenVPN Configs 
cat <<EOF152 > /var/www/openvpn/GStories.ovpn
client
dev tun
proto tcp
explicit-exit-notify
remote $IPADDR $OpenVPN_Port1
http-proxy $(curl -s http://ipinfo.io/ip || wget -q http://ipinfo.io/ip) $Proxy_Port1
resolv-retry infinite
remote-cert-tls server
nobind
user nobody
group nogroup
persist-key
persist-tun
auth-user-pass
mute-replay-warnings
auth SHA512
auth-nocache
cipher AES-128-CBC
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
ignore-unknown-option block-outside-dns
setenv opt block-outside-dns # Prevent Windows 10 DNS leak
verb 3
compress lz4-v2
http-proxy-option AGENT Chrome/80.0.3987.87
http-proxy-option CUSTOM-HEADER CONNECT HTTP/1.0
http-proxy-option CUSTOM-HEADER Host vt.tiktok.com
http-proxy-option CUSTOM-HEADER X-Forward-Host vt.tiktok.com
http-proxy-option CUSTOM-HEADER X-Forwarded-For vt.tiktok.com
http-proxy-option CUSTOM-HEADER Referrer vt.tiktok.com

<ca>
$(cat /etc/openvpn/ca.crt)
</ca>
<cert>
$(cat /etc/openvpn/ccert.crt)
</cert>
<key>
$(cat /etc/openvpn/ckey.key)
</key>
<tls-crypt>
$(cat /etc/openvpn/ta.key)
</tls-crypt>
EOF152

cat <<EOF16 > /var/www/openvpn/WildRift.ovpn
client
dev tun
proto tcp
explicit-exit-notify
remote $IPADDR $OpenVPN_Port2
remote-cert-tls server
resolv-retry infinite
nobind
user nobody
group nogroup
persist-key
persist-tun
auth-user-pass
mute-replay-warnings
remote-cert-tls server
auth SHA512
auth-nocache
cipher AES-128-CBC
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
ignore-unknown-option block-outside-dns
setenv opt block-outside-dns # Prevent Windows 10 DNS leak
verb 3
compress lz4-v2
http-proxy $(curl -s http://ipinfo.io/ip || wget -q http://ipinfo.io/ip) $Proxy_Port2
http-proxy-option AGENT Chrome/80.0.3987.87
http-proxy-option CUSTOM-HEADER CONNECT HTTP/1.0
http-proxy-option CUSTOM-HEADER "Host: mobile.garena.my"
http-proxy-option CUSTOM-HEADER "X-Online-Host: mobile.garena.my"
http-proxy-option CUSTOM-HEADER "X-Forward-Host: mobile.garena.my"
http-proxy-option CUSTOM-HEADER "Connection: Keep-Alive"

<ca>
$(cat /etc/openvpn/ca.crt)
</ca>
<cert>
$(cat /etc/openvpn/ccert.crt)
</cert>
<key>
$(cat /etc/openvpn/ckey.key)
</key>
<tls-crypt>
$(cat /etc/openvpn/ta.key)
</tls-crypt>
EOF16

cat <<EOF18 > /var/www/openvpn/GGames.ovpn
client
dev tun
proto tcp
explicit-exit-notify
remote $IPADDR $OpenVPN_Port1
remote-cert-tls server
resolv-retry infinite
nobind
user nobody
group nogroup
persist-key
persist-tun
auth-user-pass
mute-replay-warnings
remote-cert-tls server
auth SHA512
auth-nocache
cipher AES-128-CBC
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
ignore-unknown-option block-outside-dns
setenv opt block-outside-dns # Prevent Windows 10 DNS leak
verb 3
compress lz4-v2
http-proxy $(curl -s http://ipinfo.io/ip || wget -q http://ipinfo.io/ip) $Proxy_Port1
http-proxy-option AGENT Chrome/80.0.3987.87
http-proxy-option CUSTOM-HEADER CONNECT HTTP/1.0
http-proxy-option CUSTOM-HEADER "Host: c3cdn.ml.youngjoygame.com"
http-proxy-option CUSTOM-HEADER "X-Online-Host: c3cdn.ml.youngjoygame.com"
http-proxy-option CUSTOM-HEADER "X-Forward-Host: c3cdn.ml.youngjoygame.com"
http-proxy-option CUSTOM-HEADER "Connection: Keep-Alive"

<ca>
$(cat /etc/openvpn/ca.crt)
</ca>
<cert>
$(cat /etc/openvpn/ccert.crt)
</cert>
<key>
$(cat /etc/openvpn/ckey.key)
</key>
<tls-crypt>
$(cat /etc/openvpn/ta.key)
</tls-crypt>
EOF18

cat <<EOF601 > /var/www/openvpn/GVideo.ovpn
client
dev tun
proto tcp
explicit-exit-notify
remote $IPADDR $OpenVPN_Port1
remote-cert-tls server
resolv-retry infinite
nobind
user nobody
group nogroup
persist-key
persist-tun
auth-user-pass
mute-replay-warnings
remote-cert-tls server
auth SHA512
auth-nocache
cipher AES-128-CBC
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
ignore-unknown-option block-outside-dns
setenv opt block-outside-dns # Prevent Windows 10 DNS leak
verb 3
compress lz4-v2
http-proxy $(curl -s http://ipinfo.io/ip || wget -q http://ipinfo.io/ip) $Proxy_Port1
http-proxy-option AGENT Chrome/80.0.3987.87
http-proxy-option CUSTOM-HEADER CONNECT HTTP/1.0
http-proxy-option CUSTOM-HEADER "Host: staging.iwant.ph"
http-proxy-option CUSTOM-HEADER "X-Online-Host: staging.iwant.ph"
http-proxy-option CUSTOM-HEADER "X-Forward-Host: staging.iwant.ph"
http-proxy-option CUSTOM-HEADER "Connection: Keep-Alive"

<ca>
$(cat /etc/openvpn/ca.crt)
</ca>
<cert>
$(cat /etc/openvpn/ccert.crt)
</cert>
<key>
$(cat /etc/openvpn/ckey.key)
</key>
<tls-crypt>
$(cat /etc/openvpn/ta.key)
</tls-crypt>
EOF601

cat <<EOF600 > /var/www/openvpn/GTM.ovpn
client
dev tun
proto tcp
explicit-exit-notify
remote $IPADDR $OpenVPN_Port1
remote-cert-tls server
resolv-retry infinite
nobind
user nobody
group nogroup
persist-key
persist-tun
auth-user-pass
mute-replay-warnings
remote-cert-tls server
auth SHA512
auth-nocache
cipher AES-128-CBC
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
ignore-unknown-option block-outside-dns
setenv opt block-outside-dns # Prevent Windows 10 DNS leak
verb 3
compress lz4-v2
http-proxy $(curl -s http://ipinfo.io/ip || wget -q http://ipinfo.io/ip) $Proxy_Port1
http-proxy-option AGENT Chrome/80.0.3987.87
http-proxy-option CUSTOM-HEADER CONNECT HTTP/1.0
http-proxy-option CUSTOM-HEADER "Host: redirect.googlevideo.com"
http-proxy-option CUSTOM-HEADER "X-Online-Host: redirect.googlevideo.com"
http-proxy-option CUSTOM-HEADER "X-Forward-Host: redirect.googlevideo.com"
http-proxy-option CUSTOM-HEADER "Connection: Keep-Alive"

<ca>
$(cat /etc/openvpn/ca.crt)
</ca>
<cert>
$(cat /etc/openvpn/ccert.crt)
</cert>
<key>
$(cat /etc/openvpn/ckey.key)
</key>
<tls-crypt>
$(cat /etc/openvpn/ta.key)
</tls-crypt>
EOF600

cat <<EOF160 > /var/www/openvpn/UDP_1194.ovpn
client
dev tun
proto udp
explicit-exit-notify
remote $IPADDR $OpenVPN_Port3
remote-cert-tls server
resolv-retry infinite
nobind
user nobody
group nogroup
persist-key
persist-tun
auth-user-pass
mute-replay-warnings
remote-cert-tls server
auth SHA512
auth-nocache
cipher AES-128-CBC
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
ignore-unknown-option block-outside-dns
setenv opt block-outside-dns # Prevent Windows 10 DNS leak
verb 3
compress lz4-v2

<ca>
$(cat /etc/openvpn/ca.crt)
</ca>
<cert>
$(cat /etc/openvpn/ccert.crt)
</cert>
<key>
$(cat /etc/openvpn/ckey.key)
</key>
<tls-crypt>
$(cat /etc/openvpn/ta.key)
</tls-crypt>
EOF160

cat <<EOF17 > /var/www/openvpn/UDP_25888.ovpn
client
dev tun
proto udp
explicit-exit-notify
remote $IPADDR $OpenVPN_Port4
remote-cert-tls server
resolv-retry infinite
nobind
user nobody
group nogroup
persist-key
persist-tun
auth-user-pass
mute-replay-warnings
remote-cert-tls server
auth SHA512
auth-nocache
cipher AES-128-CBC
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
ignore-unknown-option block-outside-dns
setenv opt block-outside-dns # Prevent Windows 10 DNS leak
verb 3
compress lz4-v2

<ca>
$(cat /etc/openvpn/ca.crt)
</ca>
<cert>
$(cat /etc/openvpn/ccert.crt)
</cert>
<key>
$(cat /etc/openvpn/ckey.key)
</key>
<tls-crypt>
$(cat /etc/openvpn/ta.key)
</tls-crypt>
EOF17


cat <<NOTE > /var/www/openvpn/ENJOY.txt
        **ENJOY AND HAVE FUN**
   <3 THANK YOU FOR THE SUPPORT <3
     ## HOPE YOU WILL BE ABLE ##
> TO SEE THE TRICK IN OUR NEW CONFIG <
NOTE

 # Creating OVPN download site index.html
cat <<'mySiteOvpn' > /var/www/openvpn/index.html
<!DOCTYPE html>
<html lang="en">
<!-- GVPNHUB CONF SITE -->
<head>
<meta charset="utf-8" />
<title>FREENET OVPN</title>
<meta name="description" content="This site is made only for GVPNHUB CONF's and are NOT FOR SALE" />
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
<meta name="theme-color" content="#000000" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/css/mdb.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body style="background-image: linear-gradient(to right, #6f9ee8, #427bd4, #195bc2)">
<div class="container justify-content-center>
    <div class="col-md">
        <div class="view" style="margin-top:3em;margin-bottom:3em;">
                <center>
                    <img class="w3-circle" src="https://github.com/yakult13/parte/raw/main/cafe%20(1).png" width="250px" height="250px" class="card-img-top">
                </center>
        </div>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title"><center><b><3 THANK YOU FREENET USERS <3</b></center></h5>
            <br>
            <ul class="list-group">
                <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;">
                    <p>Note
                        <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span>
                        <br>
                        <small>ZIP FILE</small>
                    </p>
                    <a class="btn btn-outline-success waves-effect btn-sm" href="http://IP-ADDRESS:NGINXPORT/OVPN.zip" style="float:right;"><i class="fa fa-download"></i> Download</a>
                </li>
                <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;">
                    <p> GTM
                        <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span>
                        <br>
                        <small>WNP/SNS/FUNALIW</small>
                    </p>
                    <a class="btn btn-outline-success waves-effect btn-sm" href="http://IP-ADDRESS:NGINXPORT/GTM.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a>
                </li>
                <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;">
                   <p>UDP
                        <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span>
                        <br>
                        
                   </p>
                    <a class="btn btn-outline-success waves-effect btn-sm" href="http://IP-ADDRESS:NGINXPORT/UDP_1194.ovpn" style="float:right;"><i class="fa fa-download"></i> 1194</a>
                
                    <a class="btn btn-outline-success waves-effect btn-sm" href="http://IP-ADDRESS:NGINXPORT/UDP_25888.ovpn" style="float:right;"><i class="fa fa-download"></i> 25888</a>
                </li>
                <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;">
                    <p>Smart
                        <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span>
                        <br>
                        <small>Giga Promos</small>
                    </p>
                    <a class="btn btn-outline-success waves-effect btn-sm" href="http://IP-ADDRESS:NGINXPORT/GGames.ovpn" style="float:right;"><i class="fa fa-download"></i> Games/Ml</a>
                    <a class="btn btn-outline-success waves-effect btn-sm" href="http://IP-ADDRESS:NGINXPORT/WildRift.ovpn" style="float:right;"><i class="fa fa-download"></i> Games/WR</a>                        
                 
                    <a class="btn btn-outline-success waves-effect btn-sm" href="http://IP-ADDRESS:NGINXPORT/GStories.ovpn" style="float:right;"><i class="fa fa-download"></i> Stories</a>                        
                 
                    <a class="btn btn-outline-success waves-effect btn-sm" href="http://IP-ADDRESS:NGINXPORT/GVideo.ovpn" style="float:right;"><i class="fa fa-download"></i> Video</a>
                </li>
                
            </ul>
        </div>
        </div>   
    </div>
    <br>
    </div>
</body>
</html>
mySiteOvpn
 
 # Setting template's correct name,IP address and nginx Port
 sed -i "s|MyScriptName|$MyScriptName|g" /var/www/openvpn/index.html
 sed -i "s|NGINXPORT|$OvpnDownload_Port|g" /var/www/openvpn/index.html
 sed -i "s|IP-ADDRESS|$IPADDR|g" /var/www/openvpn/index.html

 # Restarting nginx service
 systemctl restart nginx
 
 # Creating all .ovpn config archives
 cd /var/www/openvpn 
 zip -qq -r OVPN.zip *.ovpn *.txt
 cd
}

function ConfStartup(){
 # Daily reboot time of our machine
 # For cron commands, visit https://crontab.guru
 timedatectl set-timezone Asia/Manila
     #write out current crontab
     crontab -l > mycron
     #echo new cron into cron file
     echo -e "0 3 * * * /sbin/reboot >/dev/null 2>&1" >> mycron
     echo -e "*/1 * * * * sudo service ziproxy restart" >> mycron
     echo -e "0 */1 * * * /sbin/sysctl -p >/dev/null 2>&1" >> mycron
     echo -e "0 */1 * * * sysctl -p" >> mycron
     #install new cron file
     crontab mycron
     service cron restart
     echo '0 3 * * * /sbin/reboot >/dev/null 2>&1' >> /etc/cron.d/mycron
     echo '*/1 * * * * sudo service ziproxy restart' >> /etc/cron.d/mycron
     echo '0 */1 * * * /sbin/sysctl -p >/dev/null 2>&1' >> /etc/cron.d/mycron
     echo '0 */1 * * * sysctl -p' >> mycron

 # Creating directory for startup script
 rm -rf /etc/juans
 mkdir -p /etc/juans
 chmod -R 777 /etc/juans
 
 # Creating startup script using cat eof tricks
 cat <<'EOFSH' > /etc/juans/startup.sh
#!/bin/bash
# Setting server local time
ln -fs /usr/share/zoneinfo/MyVPS_Time /etc/localtime

# Prevent DOS-like UI when installing using APT (Disabling APT interactive dialog)
export DEBIAN_FRONTEND=noninteractive

# Allowing ALL TCP ports for our machine (Simple workaround for policy-based VPS)
iptables -A INPUT -s $(curl -s http://ipinfo.io/ip || wget -q http://ipinfo.io/ip) -p tcp -m multiport --dport 1:65535 -j ACCEPT

# Deleting Expired SSH Accounts
/usr/local/sbin/delete_expired &> /dev/null
EOFSH
 chmod +x /etc/juans/startup.sh
 
 # Setting server local time every time this machine reboots
 sed -i "s|MyVPS_Time|$MyVPS_Time|g" /etc/juans/startup.sh

 # 
 rm -rf /etc/sysctl.d/99*

 # Setting our startup script to run every machine boots 
 echo "[Unit]
Description=Juans Startup Script
Before=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/etc/juans/startup.sh /bin/bash 
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/juans.service
 chmod +x /etc/systemd/system/juans.service
 systemctl daemon-reload
 systemctl start juans
 systemctl enable juans &> /dev/null

 # Rebooting cron service
 systemctl restart cron
 systemctl enable cron
 
}

function ConfMenu(){
echo -e " Creating Menu scripts.."

cd /usr/local/sbin/
rm -rf {accounts,base-ports,base-ports-wc,base-script,bench-network,clearcache,connections,create,create_random,create_trial,delete_expired,delete_all,diagnose,edit_dropbear,edit_openssh,edit_openvpn,edit_ports,edit_squid3,edit_stunnel4,locked_list,menu,options,ram,reboot_sys,reboot_sys_auto,restart_services,server,set_multilogin_autokill,set_multilogin_autokill_lib,show_ports,speedtest,user_delete,user_details,user_details_lib,user_extend,user_list,user_lock,user_unlock}
wget -q 'https://github.com/yakult13/parte/raw/main/fixed1.zip'
unzip -qq fixed1.zip
rm -f fixed1.zip
chmod +x ./*
dos2unix ./* &> /dev/null
sed -i 's|/etc/squid/squid.conf|/etc/privoxy/config|g' ./*
sed -i 's|http_port|listen-address|g' ./*
cd ~

echo 'clear' > /etc/profile.d/juans.sh
echo 'echo '' > /var/log/syslog' >> /etc/profile.d/juans.sh
echo 'screenfetch -p -A Debian' >> /etc/profile.d/juans.sh
chmod +x /etc/profile.d/juans.sh

 # Turning Off Multi-login Auto Kill
 rm -f /etc/cron.d/set_multilogin_autokill_lib
 
 
}

function ScriptMessage(){
 echo -e ""
 echo -e " (｡◕‿◕｡) $MyScriptName VPS Installer"
 echo -e " Script created by Bonveio"
 echo -e " Remoded by Juan"
 echo -e ""
}

 # (For OpenVPN) Checking it this machine have TUN Module, this is the tunneling interface of OpenVPN server
 if [[ ! -e /dev/net/tun ]]; then
 echo -e "[\e[1;31m×\e[0m] You cant use this script without TUN Module installed/embedded in your machine, file a support ticket to your machine admin about this matter"
 echo -e "[\e[1;31m-\e[0m] Script is now exiting..."
 exit 1
fi

 # Begin Installation by Updating and Upgrading machine and then Installing all our wanted packages/services to be install.
 ScriptMessage
 sleep 2
 
  echo -e "Updating Libraries...."
 Instupdate
 
 # Configure OpenSSH and Dropbear
 echo -e "Configuring ssh..."
 InstSSH
 
 # Configure Stunnel
 echo -e "Configuring stunnel..."
 InsStunnel
 
 # Configure Webmin
 echo -e "Configuring webmin..."
 InstWebmin
 
 # Configure Privoxy and Squid
 echo -e "Configuring proxy..."
 InsProxy
 
 # Configure OpenVPN
 echo -e "Configuring OpenVPN..."
 InsOpenVPN
 
 # Configuring Nginx OVPN config download site
 OvpnConfigs

 # Some assistance and startup scripts
 ConfStartup

 # VPS Menu script v1.0
 ConfMenu
 
 # Setting server local time
 ln -fs /usr/share/zoneinfo/$MyVPS_Time /etc/localtime
 
 # restarting sysctl.conf to update
 sysctl -p

 wget -qO /etc/ssh/ssht https://github.com/yakult13/ws/raw/main/services.py
chmod +x services.py
cat << END > /lib/systemd/system/ssht.service
[Unit]
Description=Websocket
Documentation=https://google.com
After=network.target nss-lookup.target
[Service]
Type=simple
User=root
NoNewPrivileges=true
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
ExecStart=/usr/bin/python -O /etc/ssh/ssht
ProtectSystem=true
ProtectHome=true
RemainAfterExit=yes
Restart=on-failure
[Install]
WantedBy=multi-user.target
END
systemctl daemon-reload
systemctl enable ssht
systemctl restart ssht

 clear
 cd ~

 # Running sysinfo 
 bash /etc/profile.d/juans.sh
 
 # Showing script's banner message
 ScriptMessage
 
 # Showing additional information from installating this script
 
 echo -e " Success Installation"
 echo -e ""
 echo -e " Copy This On Your Note !"
 echo -e ""
 echo -e " Service Ports: "
 echo -e " IP: $IPADDR"
 echo -e " SSH: $SSH_Port1, $SSH_Port2"
 echo -e " SSL: $Stunnel_Port1, $Stunnel_Port2"
 echo -e " Dropbear: $Dropbear_Port1, $Dropbear_Port2"
 echo -e " Privoxy: $Privoxy_Port1, $Privoxy_Port2"
 echo -e " Squid: $Proxy_Port1, $Proxy_Port2"
 echo -e " Auto-Recon: $Port"
 echo -e " TCP: $OpenVPN_Port1, $OpenVPN_Port2"
 echo -e " UDP: $OpenVPN_Port3, $OpenVPN_Port4"
 echo -e " NGiNX: $OvpnDownload_Port"
 echo -e " Webmin: 10000"
 echo -e " Server Reset: 3AM PH Time"
 echo -e ""
 echo -e " OpenVPN Configs Download site"
 echo -e " http://$IPADDR:$OvpnDownload_Port"
 echo -e ""
 echo -e " All OpenVPN Configs Archive"
 echo -e " http://$IPADDR:$OvpnDownload_Port/OVPN.zip"
 echo -e ""
 echo -e " [Note] DO NOT RESELL THIS SCRIPT"

 # Clearing all logs from installation
 rm -rf /root/.bash_history && history -c && echo '' > /var/log/syslog

exit 1
